language: cpp
compiler:
- gcc
install:
# Install CMake 3
- wget https://cmake.org/files/v3.4/cmake-3.4.0-Linux-x86_64.tar.gz
- tar -xzf cmake-3.4.0-Linux-x86_64.tar.gz
- sudo cp -fR cmake-3.4.0-Linux-x86_64/* /usr
- rm -rf cmake-3.4.0-Linux-x86_64
- rm cmake-3.4.0-Linux-x86_64.tar.gz

# Download conan (REPLACE WITH LATEST VERSION LINK!)
- wget https://s3-eu-west-1.amazonaws.com/conanio/downloads/conan-ubuntu-64_0_3_0.deb -O conan.deb
- sudo dpkg -i conan.deb
- rm conan.deb

# Automatic detection of your arch, compiler, etc
- conan install --build missing
  
script:
- mkdir build
- cd build && cmake ../ -DBUILD_TEST=TRUE && cmake --build .
- ./build/bin/encryption_test

